{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdcb-{{ include "tyk-pro.fullname" . }}
  labels:
    app: mdcb-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mdcb-{{ include "tyk-pro.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mdcb-{{ include "tyk-pro.fullname" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-mdcb.yaml") . | sha256sum }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: dashboard-{{ .Chart.Name }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
        env:
          - name: TYK_MDCB_SERVEROPTIONS_USESSL
          # Enable backward compatibility to chart 0.8.1.
            value: "{{ or .Values.tls .Values.useSSL false }}"
          - name: TYK_MDCB_LISTENPORT
            value: "{{ .Values.containerPort }}"
          # Lagacy support for Redis Cluster driver. Driver dropped in v3.0.0.
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "128"
          - name: TYK_MDCB_HEALTHCHECKPORT
            value: "{{ .Values.healthcheckport }}"
          - name: TYK_MDCB_STORAGE_ADDRS
            value: {{ include "tyk-pro.redis_url" . | quote }}
          - name: TYK_MDCB_STORAGE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pro.fullname" . }} {{ end}}
                key: redisPass
          - name: TYK_MDCB_STORAGE_REDISUSESSL
            value: "{{ default "false" .Values.redis.useSSL }}"
          - name: TYK_MDCB_STORAGE_REDISSSLINSECURESKIPVERIFY
            value: "true"
          - name: TYK_MDCB_ANALYTICSCONFIG_MONGOURL
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pro.fullname" . }} {{ end}}
                key: mongoURL
          - name: TYK_MDCB_ANALYTICSCONFIG_MONGOUSESSL
            value: "{{ default "false" .Values.mongo.useSSL }}"
          - name: TYK_MDCB_FORWARDANALYTICSTOPUMP
            value: "{{ .Values.forwardAnalyticsToPump }}"
          - name: TYK_MDCB_LICENSE
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pro.fullname" . }} {{ end}}
                key: MDCBLicense
          {{- if .Values.extraEnvs }}
          {{- toYaml .Values.extraEnvs| nindent 10 }}
          {{- end }}
        resources:
        {{ toYaml .Values.resources | indent 12 }}
        command: ["/opt/tyk-sink/tyk-sink", "--c=/etc/tyk-sink/tyk_sink.conf"]
        workingDir: /opt/tyk-sink
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
          - name: tyk-mdcb-conf
            mountPath: /etc/tyk-sink
          {{- if .Values.mounts }}
          {{- range $secret := .Values.mounts }}
          - name: {{ $.Release.Name }}-mdcb-secret-{{ $secret.name }}
            mountPath: {{ $secret.mountPath }}
          {{- end }}
          {{- end }}
        livenessProbe:
          httpGet:
            scheme: "HTTP"
            path: /health
            port: {{ .Values.healthcheckport }}
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            scheme: "HTTP"
            path: /health
            port: {{ .Values.healthcheckport }}
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      volumes:
        - name: tyk-mdcb-conf
          configMap:
            name: mdcb-conf-{{ include "tyk-pro.fullname" . }}
            items:
              - key: tyk_sink.conf
                path: tyk_sink.conf
        - name: {{ .Release.Name }}-default-cert
          secret:
            secretName: {{ .Release.Name }}-default-cert
        {{- if .Values.mounts }}
        {{- range $secret := .Values.mounts }}
        - name: {{ $.Release.Name }}-mdcb-secret-{{ $secret.name }}
          secret:
            secretName: {{ $.Release.Name }}-mdcb-secret-{{ $secret.name }}
        {{- end }}
        {{- end }}
{{- end }}
