{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pump-{{ include "tyk-headless.fullname" . }}
  labels:
    app: pump-{{ include "tyk-headless.fullname" . }}
    chart: {{ include "tyk-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pump-{{ include "tyk-headless.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pump-{{ include "tyk-headless.fullname" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-pump.yaml") . | sha256sum }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
      containers:
      - name: pump-{{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: "/opt/tyk-pump"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
        env:
          # Lagacy support for Redis Cluster driver. Driver dropped in v3.0.0.
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "128"
          {{- if .Values.mongo.enabled }}
          - name: PMP_MONGO_MONGOURL
            value: {{ include "tyk-headless.mongo_url" . | quote }}
          - name: PMP_MONGO_MONGOUSESSL
            value: "{{ default "false" .Values.mongo.useSSL }}"
          - name: PMP_MONGOAGG_MONGOURL
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end}}
                key: mongoURL
          - name: PMP_MONGOAGG_MONGOUSESSL
            value:  "{{ default "false" .Values.mongo.useSSL }}"
          {{- end }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ADDRS
            {{- if and .Values.redis.host .Values.redis.port }}
            value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
            {{- else }}
            value: "{{ join "," .Values.redis.addrs }}"
            {{- end }}
          {{ if .Values.redis.enableSentinel }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_SENTINELPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
                key: redisSentinelPass
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MASTERNAME
            value: "{{- .Values.redis.masterName -}}"
          {{ else if .Values.redis.enableCluster }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ENABLECLUSTER
            value: "true"
          {{ else }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MASTERNAME
            value: ""
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ENABLECLUSTER
            value: "false"
          {{ end }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end}}
                key: redisPass
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_REDISUSESSL
            value: "{{ default "false" .Values.redis.useSSL }}"
        {{- if .Values.extraEnvs }}
        {{- range $env := .Values.extraEnvs }}
          - name: {{ $env.name }}
            value: {{ $env.value | quote }}
        {{- end }}
        {{- end }}
        command: ["/opt/tyk-pump/tyk-pump", "-c", "/etc/tyk-pump/pump.conf"]
        volumeMounts:
          - name: tyk-pump-conf
            mountPath: /etc/tyk-pump
          {{- if .Values.mounts }}
          {{- range $secret := .Values.mounts }}
          - name: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
            mountPath: {{ $secret.mountPath }}
          {{- end }}
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      volumes:
        - name: tyk-pump-conf
          configMap:
            name: pump-conf-{{ include "tyk-headless.fullname" . }}
            items:
              - key: pump.conf
                path: pump.conf
        {{- if .Values.mounts }}
        {{- range $secret := .Values.mounts }}
        - name: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
          secret:
            secretName: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
        {{- end }}
        {{- end }}
{{- end }}
