{{- if .Values.mounts }}
{{- range $secret := .Values.mounts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-gateway-secret-{{ $secret.name }}
  labels:
    app: gateway-secret-{{ $secret.name }}-{{ include "tyk-headless.fullname" $ }}
    chart: {{ include "tyk-headless.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: Opaque
data:
  {{ $secret.filename }}: |-
{{ $.Files.Get (printf "mounts/%s" $secret.filename) | b64enc | indent 4 }}
---
{{- end }}
{{- end }}
